import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#f8f9ff",
        foreground: "#001d36",
        "on-background": "#001d36",
        surface: "#f8f9ff",
        "surface-dim": "#c2dcff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5efff",
        "surface-container-low": "#eef4ff",
        "surface-container-high": "#dbe9ff",
        "surface-container-highest": "#d1e4ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d1e4ff",
        "on-surface": "#001d36",
        "on-surface-variant": "#3e484f",
        "outline-variant": "#bdc8d1",
        outline: "#6e7980",
        primary: {
          DEFAULT: "#00668a",
          container: "#38bdf8",
          foreground: "#ffffff",
          fixed: "#c4e7ff",
          "fixed-dim": "#7bd0ff",
        },
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "primary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#7bd0ff",
        secondary: {
          DEFAULT: "#4d6268",
          container: "#cde3eb",
          foreground: "#ffffff",
        },
        "secondary-container": "#cde3eb",
        "on-secondary-container": "#51666d",
        tertiary: {
          DEFAULT: "#006b5f",
          container: "#30c5b3",
          foreground: "#ffffff",
        },
        "tertiary-container": "#30c5b3",
        "on-tertiary-container": "#004d44",
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
          foreground: "#ffffff",
        },
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#001d36",
        },
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "0.75rem",
        md: "0.5rem",
        sm: "0.25rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
