'use client'

import React, { useEffect, useState } from 'react'
import { FileText, Download, Share2, Shield, CheckCircle2, ChevronRight, X } from 'lucide-react'
import { format } from 'date-fns'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'

import {
  Dialog,
  DialogContent,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Badge } from '@/components/ui/badge'

interface FSSAIReportModalProps {
  scan: any
  defaultOpen?: boolean
}

export default function FSSAIReportModal({ scan, defaultOpen = false }: FSSAIReportModalProps) {
  const [open, setOpen] = useState(defaultOpen)

  useEffect(() => {
    if (defaultOpen) {
      setOpen(true)
    }
  }, [defaultOpen])

  const handlePrint = () => {
    window.print()
  }

  const handleShare = async () => {
    const summary = `MilkGuard Scan Report
Vendor: ${scan.vendors?.name || 'Unlisted Sample'}
Location: ${scan.vendors?.city || 'Jaipur'}
Result: ${scan.result_tier === 'safe' ? 'PASS' : 'FAIL'}
Score: ${scan.safety_score}/100
Blockchain Verified: https://amoy.polygonscan.com/tx/${scan.tx_hash || 'pending'}
Generated by MilkGuard`

    try {
      await navigator.clipboard.writeText(summary)
      toast.success("Copied to clipboard", { description: "Report summary is ready to share." })
    } catch (err) {
      toast.error("Failed to copy")
    }
  }

  const generatedId = `MG-${new Date(scan.created_at).getTime()}`

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="w-full h-14 rounded-3xl border-slate-200 text-slate-600 font-black uppercase tracking-tighter gap-3 bg-white hover:bg-slate-50 print:hidden">
          <FileText size={20} className="text-[#60A5FA]" />
          Generate FSSAI Report
        </Button>
      </DialogTrigger>
      
      {/* 
        We use an extreme z-index and fixed position for printing logic, 
        but normally display inside DialogContent via shadcn 
      */}
      <DialogContent className="max-w-2xl p-0 overflow-hidden bg-white [&>button]:hidden print:fixed print:inset-0 print:block print:w-full print:h-full print:m-0 print:p-0 print:border-none print:shadow-none print:z-[9999]">
        <div className="flex justify-between items-center p-4 bg-slate-50 border-b print:hidden">
           <h2 className="text-sm font-black text-slate-800 uppercase tracking-widest flex items-center gap-2">
             <FileText size={16} className="text-[#60A5FA]" />
             Document Preview
           </h2>
           <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handleShare} className="h-8 gap-2 uppercase tracking-tighter font-bold text-[10px]">
                <Share2 size={12} /> Share
              </Button>
              <Button size="sm" onClick={handlePrint} className="h-8 gap-2 bg-[#60A5FA] hover:bg-blue-600 uppercase tracking-tighter font-bold text-[10px]">
                <Download size={12} /> Download PDF
              </Button>
              <Button variant="ghost" size="icon" onClick={() => setOpen(false)} className="h-8 w-8 ml-2">
                <X size={16} />
              </Button>
           </div>
        </div>

        {/* Printable Report Container */}
        <div className="p-10 print:p-0 overflow-y-auto max-h-[80vh] print:max-h-none print:overflow-visible bg-white text-black print-document" id={"print-report"}>
           
           {/* HEADER */}
           <div className="flex justify-between items-start mb-10 pb-6 border-b-2 border-black">
              <div>
                 <div className="flex items-center gap-2 mb-2">
                   <div className="w-8 h-8 bg-black rounded-lg flex items-center justify-center">
                      <Shield size={16} className="text-white" />
                   </div>
                   <h1 className="text-2xl font-black tracking-tighter uppercase leading-none">MilkGuard</h1>
                 </div>
                 <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gray-500">
                    Targeted Spectral Analysis
                 </p>
              </div>
              <div className="text-right">
                 <h2 className="text-lg font-black uppercase tracking-tight mb-1">Milk Quality Test Report</h2>
                 <p className="text-xs font-medium text-gray-600 mb-0.5">Report ID: <span className="font-mono font-bold text-black">{generatedId}</span></p>
                 <p className="text-xs font-medium text-gray-600">Date: <span className="font-bold text-black">{format(new Date(scan.created_at), 'dd MMM yyyy, HH:mm')}</span></p>
              </div>
           </div>

           {/* VENDOR DETAILS */}
           <div className="mb-8">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-black/50 mb-3 block border-b border-black/10 pb-1 w-full">Vendor Information</h3>
              <div className="grid grid-cols-2 gap-4">
                 <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">Name</p>
                    <p className="font-black text-lg uppercase">{scan.vendors?.name || 'Unlisted / Home Sample'}</p>
                 </div>
                 <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">Entity Reference</p>
                    <p className="font-mono text-sm font-bold">{scan.vendors?.id || 'N/A'}</p>
                 </div>
                 <div className="col-span-2">
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">Location Details</p>
                    <p className="text-sm font-medium">
                       {scan.vendors?.area ? `${scan.vendors.area}, ` : ''}{scan.vendors?.city || 'Jaipur'}
                    </p>
                 </div>
              </div>
           </div>

           {/* TEST RESULTS */}
           <div className="mb-8">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-black/50 mb-3 block border-b border-black/10 pb-1 w-full">Analytical Results</h3>
              <div className="flex items-center justify-between mb-6 bg-gray-50 p-4 border border-gray-200">
                 <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-1">Methodology</p>
                    <p className="text-sm font-black">IoT Spectral Analysis via ESP32</p>
                 </div>
                 <div className="text-center px-6 border-l border-r border-gray-200">
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-1">Purity Score</p>
                    <p className="text-2xl font-black leading-none">{scan.safety_score}/100</p>
                 </div>
                 <div className="text-right">
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-1">Result Status</p>
                    <p className={cn("text-2xl font-black uppercase tracking-tighter leading-none", scan.result_tier === 'safe' ? "text-green-600" : "text-red-600")}>
                      {scan.result_tier === 'safe' ? 'PASS' : 'FAIL'}
                    </p>
                 </div>
              </div>
              
              <div className="pl-4 border-l-2 border-black/10">
                 <p className="text-xs font-bold uppercase tracking-wider text-black mb-2">Detected Contaminants:</p>
                 {scan.adulterant_results?.filter((r: any) => r.detected).length > 0 ? (
                   <ul className="space-y-1">
                     {scan.adulterant_results.filter((r: any) => r.detected).map((r: any) => (
                       <li key={r.id} className="text-sm flex items-center gap-2 text-red-600 font-bold">
                         <span className="w-1.5 h-1.5 rounded-full bg-red-600" />
                         {r.name} — {r.detected_value}{r.unit}
                       </li>
                     ))}
                   </ul>
                 ) : (
                   <p className="text-sm font-bold text-green-600">None detected within instrument limits.</p>
                 )}
              </div>
           </div>

           {/* FSSAI COMPLIANCE */}
           <div className="mb-8">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-black/50 mb-3 block border-b border-black/10 pb-1 w-full">Regulatory Compliance</h3>
              <div className="flex gap-4">
                 <div className="flex-1">
                    <p className="text-sm font-bold text-black mb-1">Ref: IS 1479 (Methods of Test for Dairy Industry)</p>
                    <p className="text-xs text-black/70 mb-2">This sample was analyzed against standard permissible limits for water, urea, detergents, and synthetic thickeners.</p>
                    {scan.result_tier !== 'safe' && (
                      <p className="text-xs font-bold text-red-600 bg-red-50 p-2 border border-red-100 uppercase tracking-wider">
                         Action Required: Report to nearest FSSAI office or call 1800-112-100 immediately.
                      </p>
                    )}
                 </div>
                 <div className="shrink-0 flex items-center justify-center border-2 border-black p-4 w-32 h-32 rotate-[-5deg]">
                    <span className={cn(
                      "text-xl font-black uppercase tracking-widest text-center leading-tight",
                      scan.result_tier === 'safe' ? "text-green-600" : "text-red-600"
                    )}>
                      {scan.result_tier === 'safe' ? 'Compliant' : 'Non\\nCompliant'}
                    </span>
                 </div>
              </div>
           </div>

           {/* BLOCKCHAIN LEDGER */}
           <div className="mb-12">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-black/50 mb-3 block border-b border-black/10 pb-1 w-full">Immutability Ledger</h3>
              <div className="bg-gray-50 border border-gray-200 p-4 rounded text-sm">
                 <div className="flex items-center gap-2 mb-2 font-bold text-green-600 uppercase tracking-widest text-[10px]">
                    <CheckCircle2 size={12} /> Immutably Recorded on Blockchain
                 </div>
                 <div className="grid grid-cols-[100px_1fr] gap-1 text-xs">
                    <span className="font-bold text-gray-500">Network:</span>
                    <span className="font-medium text-black">Polygon Amoy Testnet</span>
                    
                    <span className="font-bold text-gray-500">Tx Hash:</span>
                    <span className="font-mono text-[10px] text-black break-all">{scan.tx_hash || 'Pending validation'}</span>
                 </div>
              </div>
           </div>

           {/* FOOTER */}
           <div className="text-center pt-6 border-t border-black/10">
              <p className="text-[10px] font-bold text-black/40 uppercase tracking-widest mb-1">
                 This report was automatically generated by the MilkGuard Framework.
              </p>
              <p className="text-[10px] font-bold text-black/40 uppercase tracking-widest mb-1">
                 For verification visit: amoy.polygonscan.com/tx/{scan.tx_hash || 'pending'}
              </p>
              <p className="text-[8px] font-mono text-black/30">
                 {generatedId} • {new Date().toISOString()}
              </p>
           </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
